/** API 路径集中常量，避免页面散落魔法字符串 */
export const API = {
  providers: '/api/providers',
  provider: (id: string) => `/api/providers/${id}`,
  providerTest: (id: string) => `/api/providers/${id}/test`,
  providerModels: (id: string) => `/api/providers/${id}/models`,
  model: (id: string) => `/api/models/${id}`,
  settings: '/api/settings',
  assistants: '/api/assistants',
  assistant: (id: string) => `/api/assistants/${id}`,
  assistantReorder: '/api/assistants/reorder',
  conversations: '/api/conversations',
  conversation: (id: string) => `/api/conversations/${id}`,
  messages: (id: string) => `/api/conversations/${id}/messages`,
  messageFeedback: (conversationId: string, messageId: string) =>
    `/api/conversations/${conversationId}/messages/${messageId}`,
  chatStream: '/api/chat/stream',
  chatProactive: '/api/chat/proactive',
  knowledgeBases: '/api/knowledge-bases',
  knowledgeBase: (id: string) => `/api/knowledge-bases/${id}`,
  documents: (kbId: string) => `/api/knowledge-bases/${kbId}/documents`,
  kbConflicts: (kbId: string) => `/api/knowledge-bases/${kbId}/conflicts`,
  kbDuplicates: (kbId: string) => `/api/knowledge-bases/${kbId}/duplicates`,
  clip: (kbId: string) => `/api/knowledge-bases/${kbId}/clip`,
  document: (id: string) => `/api/documents/${id}`,
  attachments: '/api/attachments',
  attachment: (id: string) => `/api/attachments/${id}`,
  memories: '/api/memories',
  memory: (id: string) => `/api/memories/${id}`,
  memoryClear: '/api/memories/clear',
  mcpServers: '/api/mcp/servers',
  mcpServer: (id: string) => `/api/mcp/servers/${id}`,
  mcpTools: '/api/mcp/tools',
  skills: '/api/skills',
  skill: (id: string) => `/api/skills/${id}`,
  toolConfirm: '/api/tools/confirm',
  toolPermissions: '/api/tools/permissions',
  toolPermission: (id: string) => `/api/tools/permissions/${id}`,
  toolBreakers: '/api/tools/breakers',
  toolDebug: '/api/tools/debug',
  tasks: '/api/tasks',
  taskList: (conversationId: string) => `/api/tasks?conversationId=${conversationId}`,
  task: (id: string) => `/api/tasks/${id}`,
  taskEvents: (id: string) => `/api/tasks/${id}/events`,
  taskControl: (id: string) => `/api/tasks/${id}/control`,
  taskStopAll: '/api/tasks/stop-all',
  // v0.8 Flow Studio
  flows: '/api/flows',
  flow: (id: string) => `/api/flows/${id}`,
  flowVersions: (id: string) => `/api/flows/${id}/versions`,
  flowValidate: (id: string) => `/api/flows/${id}/validate`,
  flowPublish: (id: string) => `/api/flows/${id}/publish`,
  flowRuns: (id: string) => `/api/flows/${id}/runs`,
  flowRun: (runId: string) => `/api/flows/runs/${runId}`,
  flowRunEvents: (runId: string) => `/api/flows/runs/${runId}/events`,
  flowRunHuman: (runId: string) => `/api/flows/runs/${runId}/human`,
  flowRunToolConfirm: (runId: string) => `/api/flows/runs/${runId}/tool-confirm`,
  flowRunControl: (runId: string) => `/api/flows/runs/${runId}/control`,
  // v0.9 对外服务端点（内部管理面）
  flowEndpoint: (id: string) => `/api/flows/${id}/endpoint`,
  flowEndpointRotate: (id: string) => `/api/flows/${id}/endpoint/rotate`,
  // v0.9 M4 运行记录与重放
  flowRunsCenter: '/api/flow-runs',
  flowRunReplay: (runId: string) => `/api/flows/runs/${runId}/replay`,
  // v1.0 语音
  voiceSettings: '/api/voice/settings',
  voiceTts: '/api/voice/tts',
  voiceAsr: '/api/voice/asr',
  voiceModelStatus: '/api/voice/models/status',
  voiceModelDownload: '/api/voice/models/download',
} as const;

export const QUERY_KEYS = {
  providers: ['providers'] as const,
  models: (providerId: string) => ['models', providerId] as const,
  modelsAll: ['models', 'all'] as const,
  settings: ['settings'] as const,
  assistants: ['assistants'] as const,
  conversations: ['conversations'] as const,
  messages: (conversationId: string) => ['messages', conversationId] as const,
  knowledgeBases: ['knowledge-bases'] as const,
  documents: (kbId: string) => ['documents', kbId] as const,
  kbGovernance: (kbId: string) => ['kb-governance', kbId] as const,
  attachment: (id: string) => ['attachment', id] as const,
  memories: ['memories'] as const,
  mcpServers: ['mcp-servers'] as const,
  mcpTools: ['mcp-tools'] as const,
  skills: ['skills'] as const,
  toolPermissions: ['tool-permissions'] as const,
  toolBreakers: ['tool-breakers'] as const,
  toolDebug: ['tool-debug'] as const,
  tasks: ['tasks'] as const,
  tasksByConversation: (conversationId: string) =>
    ['tasks', { conversationId }] as const,
  task: (id: string) => ['task', id] as const,
  flows: ['flows'] as const,
  flow: (id: string) => ['flows', id] as const,
  flowRun: (id: string) => ['flow-run', id] as const,
  flowEndpoint: (id: string) => ['flow-endpoint', id] as const,
  voiceSettings: ['voice-settings'] as const,
  voiceModelStatus: ['voice-model-status'] as const,
};
