// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.
// Bump the version in the root package.json, then run `pnpm sync-version`.
/** 应用版本单一事实源（root package.json version 的镜像） */
export const APP_VERSION = '1.1.0';
