#!/usr/bin/env node
/**
 * 版本号单一事实源同步脚本。
 *
 * 真源：root package.json 的 version。
 * 同步：apps/web、apps/desktop 的 package.json
 *       packages/shared/src/version.ts（APP_VERSION，MCP serverInfo/clientInfo 等运行时读取）
 *
 * 用法：
 *   node scripts/sync-version.mjs          # 写入同步
 *   node scripts/sync-version.mjs --check   # 只校验不改（CI 用；不一致 exit 1）
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');

const targets = ['apps/web/package.json', 'apps/desktop/package.json'];
const versionFile = 'packages/shared/src/version.ts';

function readJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
}

function writeJson(rel, data) {
  fs.writeFileSync(path.join(root, rel), `${JSON.stringify(data, null, 2)}\n`);
}

function expectedVersionFile(version) {
  return `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.
// Bump the version in the root package.json, then run \`pnpm sync-version\`.
/** 应用版本单一事实源（root package.json version 的镜像） */
export const APP_VERSION = '${version}';
`;
}

const rootPkg = readJson('package.json');
const version = rootPkg.version;
if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`invalid semver in root package.json: ${version}`);
  process.exit(1);
}

const drifts = [];

for (const rel of targets) {
  const pkg = readJson(rel);
  if (pkg.version !== version) {
    drifts.push(`${rel}: ${pkg.version} -> ${version}`);
    if (!checkOnly) {
      pkg.version = version;
      writeJson(rel, pkg);
    }
  }
}

const versionPath = path.join(root, versionFile);
const currentVersionSource = fs.readFileSync(versionPath, 'utf8');
const expected = expectedVersionFile(version);
if (currentVersionSource !== expected) {
  const m = currentVersionSource.match(/APP_VERSION = '([^']+)'/);
  drifts.push(`${versionFile}: ${m?.[1] ?? '(missing)'} -> ${version}`);
  if (!checkOnly) fs.writeFileSync(versionPath, expected);
}

if (drifts.length === 0) {
  console.log(`version in sync: ${version}`);
} else if (checkOnly) {
  console.error('version drift detected (run `pnpm sync-version`):');
  for (const d of drifts) console.error(`  - ${d}`);
  process.exit(1);
} else {
  console.log(`version synced to ${version}:`);
  for (const d of drifts) console.log(`  - ${d}`);
}
